name: Deploy BackendExpressTest
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t arrokoth7412/express_test  .

      - name: Publish Image to Docker Hub
        run: docker push arrokoth7412/express_test:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull arrokoth7412/express_test:latest

      - name: Delete old container
        run: docker rm -f express-container

      - name: Remove previous Docker image
        run: |
          docker image prune -f --filter "until=24h"
          docker rmi arrokoth7412/express_test:latest

      - name: Create .env file on the server
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Run Docker Container
        run: docker run --restart=always -d -p 3000:3000 --name ${{ env.PRODUCTION_NAME }}-container arrokoth7412/express_test
